// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

/**
 * Config represents the application configuration
 */
export class Config {
    /**
     * Creates a new Config instance.
     * @param {Partial<Config>} [$$source = {}] - The source object to create the Config.
     */
    constructor($$source = {}) {
        if (!("deviceId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["deviceId"] = "";
        }
        if (!("deviceName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["deviceName"] = "";
        }
        if (!("port" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["port"] = 0;
        }
        if (!("syncIntervalMins" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["syncIntervalMins"] = 0;
        }
        if (!("globalExclusions" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["globalExclusions"] = [];
        }
        if (!("peers" in $$source)) {
            /**
             * @member
             * @type {(models$0.Peer | null)[]}
             */
            this["peers"] = [];
        }
        if (!("folderPairs" in $$source)) {
            /**
             * @member
             * @type {(models$0.FolderPair | null)[]}
             */
            this["folderPairs"] = [];
        }
        if (!("autoSync" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["autoSync"] = false;
        }
        if (!("startOnLogin" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["startOnLogin"] = false;
        }
        if (!("showNotifications" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["showNotifications"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Config instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Config}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType0;
        const $$createField5_0 = $$createType3;
        const $$createField6_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("globalExclusions" in $$parsedSource) {
            $$parsedSource["globalExclusions"] = $$createField4_0($$parsedSource["globalExclusions"]);
        }
        if ("peers" in $$parsedSource) {
            $$parsedSource["peers"] = $$createField5_0($$parsedSource["peers"]);
        }
        if ("folderPairs" in $$parsedSource) {
            $$parsedSource["folderPairs"] = $$createField6_0($$parsedSource["folderPairs"]);
        }
        return new Config(/** @type {Partial<Config>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = models$0.Peer.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = models$0.FolderPair.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $Create.Array($$createType5);
