// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App struct
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "./internal/config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "./internal/models/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as sync$0 from "./internal/sync/models.js";

/**
 * AcceptPairing accepts a pairing request
 * @param {string} peerID
 * @returns {$CancellablePromise<void>}
 */
export function AcceptPairing(peerID) {
    return $Call.ByID(2350329267, peerID);
}

/**
 * AddFolderPair adds a new folder pair
 * @param {string} peerID
 * @param {string} localPath
 * @param {string} remotePath
 * @returns {$CancellablePromise<models$0.FolderPair | null>}
 */
export function AddFolderPair(peerID, localPath, remotePath) {
    return $Call.ByID(440578476, peerID, localPath, remotePath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * AnalyzeFolderPair returns a preview of what would be synced
 * @param {string} folderPairID
 * @returns {$CancellablePromise<sync$0.SyncPreview | null>}
 */
export function AnalyzeFolderPair(folderPairID) {
    return $Call.ByID(3974061087, folderPairID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * FormatBytes formats bytes as human-readable string
 * @param {number} bytes
 * @returns {$CancellablePromise<string>}
 */
export function FormatBytes(bytes) {
    return $Call.ByID(3643935769, bytes);
}

/**
 * FormatDuration formats a duration as human-readable string
 * @param {number} seconds
 * @returns {$CancellablePromise<string>}
 */
export function FormatDuration(seconds) {
    return $Call.ByID(1027163302, seconds);
}

/**
 * GeneratePairingCode generates a new pairing code
 * @returns {$CancellablePromise<string>}
 */
export function GeneratePairingCode() {
    return $Call.ByID(1671898891);
}

/**
 * GetAggregateProgress returns the aggregate sync progress (throttled)
 * @returns {$CancellablePromise<models$0.AggregateProgress | null>}
 */
export function GetAggregateProgress() {
    return $Call.ByID(2286096273).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * GetAppVersion returns the application version
 * @returns {$CancellablePromise<string>}
 */
export function GetAppVersion() {
    return $Call.ByID(1780012486);
}

/**
 * GetConfig returns the current configuration
 * @returns {$CancellablePromise<config$0.Config | null>}
 */
export function GetConfig() {
    return $Call.ByID(1200034045).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * GetCurrentPairingCode returns the current pairing code
 * @returns {$CancellablePromise<string>}
 */
export function GetCurrentPairingCode() {
    return $Call.ByID(1994544353);
}

/**
 * GetDataDirectory returns the app data directory
 * @returns {$CancellablePromise<string>}
 */
export function GetDataDirectory() {
    return $Call.ByID(1415277486);
}

/**
 * GetFolderPairs returns all folder pairs
 * @returns {$CancellablePromise<(models$0.FolderPair | null)[]>}
 */
export function GetFolderPairs() {
    return $Call.ByID(574249928).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * GetHomeDirectory returns the user's home directory
 * @returns {$CancellablePromise<string>}
 */
export function GetHomeDirectory() {
    return $Call.ByID(2225270255);
}

/**
 * GetPeers returns all discovered and paired peers
 * @returns {$CancellablePromise<(models$0.Peer | null)[]>}
 */
export function GetPeers() {
    return $Call.ByID(1748826452).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType11($result);
    }));
}

/**
 * GetRecentEvents returns recent sync events
 * @returns {$CancellablePromise<(sync$0.SyncEvent | null)[]>}
 */
export function GetRecentEvents() {
    return $Call.ByID(607076933).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType14($result);
    }));
}

/**
 * GetSyncProgress returns the current transfer progress (legacy, per-file)
 * @returns {$CancellablePromise<models$0.TransferProgress | null>}
 */
export function GetSyncProgress() {
    return $Call.ByID(4046381531).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType16($result);
    }));
}

/**
 * GetSyncStatus returns the current sync status
 * @returns {$CancellablePromise<{ [_: string]: any }>}
 */
export function GetSyncStatus() {
    return $Call.ByID(2747611114).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType17($result);
    }));
}

/**
 * IsPaused returns whether sync is paused
 * @returns {$CancellablePromise<boolean>}
 */
export function IsPaused() {
    return $Call.ByID(2583346675);
}

/**
 * MinimizeToTray hides the window to system tray
 * @returns {$CancellablePromise<void>}
 */
export function MinimizeToTray() {
    return $Call.ByID(2872916804);
}

/**
 * OpenDataDirectory opens the data directory in Finder
 * @returns {$CancellablePromise<void>}
 */
export function OpenDataDirectory() {
    return $Call.ByID(992001628);
}

/**
 * PathExists checks if a path exists
 * @param {string} path
 * @returns {$CancellablePromise<boolean>}
 */
export function PathExists(path) {
    return $Call.ByID(20277526, path);
}

/**
 * Pause pauses automatic sync
 * @returns {$CancellablePromise<void>}
 */
export function Pause() {
    return $Call.ByID(1037007909);
}

/**
 * QuitApp quits the application
 * @returns {$CancellablePromise<void>}
 */
export function QuitApp() {
    return $Call.ByID(3730234565);
}

/**
 * RefreshPeers triggers a peer discovery refresh
 * @returns {$CancellablePromise<void>}
 */
export function RefreshPeers() {
    return $Call.ByID(1532285337);
}

/**
 * RejectPairing rejects a pairing request
 * @param {string} peerID
 * @returns {$CancellablePromise<void>}
 */
export function RejectPairing(peerID) {
    return $Call.ByID(3200575234, peerID);
}

/**
 * RemoveFolderPair removes a folder pair
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function RemoveFolderPair(id) {
    return $Call.ByID(3518119929, id);
}

/**
 * RequestPairing initiates pairing with a peer
 * @param {string} peerID
 * @param {string} code
 * @returns {$CancellablePromise<void>}
 */
export function RequestPairing(peerID, code) {
    return $Call.ByID(3894435126, peerID, code);
}

/**
 * Resume resumes automatic sync
 * @returns {$CancellablePromise<void>}
 */
export function Resume() {
    return $Call.ByID(2476070530);
}

/**
 * SelectFolder opens a folder picker dialog
 * @returns {$CancellablePromise<string>}
 */
export function SelectFolder() {
    return $Call.ByID(237181597);
}

/**
 * ShowWindow shows and focuses the main window
 * @returns {$CancellablePromise<void>}
 */
export function ShowWindow() {
    return $Call.ByID(31117496);
}

/**
 * SyncFolderPair syncs a specific folder pair
 * @param {string} folderPairID
 * @returns {$CancellablePromise<void>}
 */
export function SyncFolderPair(folderPairID) {
    return $Call.ByID(3520587498, folderPairID);
}

/**
 * SyncNow triggers an immediate sync for all folder pairs
 * @returns {$CancellablePromise<void>}
 */
export function SyncNow() {
    return $Call.ByID(2954670258);
}

/**
 * UnpairPeer removes pairing with a peer
 * @param {string} peerID
 * @returns {$CancellablePromise<void>}
 */
export function UnpairPeer(peerID) {
    return $Call.ByID(1922999266, peerID);
}

/**
 * UpdateAutoSync updates the auto sync setting
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function UpdateAutoSync(enabled) {
    return $Call.ByID(4126172572, enabled);
}

/**
 * UpdateDeviceName updates the device name
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function UpdateDeviceName(name) {
    return $Call.ByID(3869163765, name);
}

/**
 * UpdateFolderPair updates a folder pair
 * @param {string} id
 * @param {boolean} enabled
 * @param {string[]} exclusions
 * @returns {$CancellablePromise<void>}
 */
export function UpdateFolderPair(id, enabled, exclusions) {
    return $Call.ByID(693009948, id, enabled, exclusions);
}

/**
 * UpdateGlobalExclusions updates the global exclusion patterns
 * @param {string[]} patterns
 * @returns {$CancellablePromise<void>}
 */
export function UpdateGlobalExclusions(patterns) {
    return $Call.ByID(3170759298, patterns);
}

/**
 * UpdateSyncInterval updates the sync interval
 * @param {number} mins
 * @returns {$CancellablePromise<void>}
 */
export function UpdateSyncInterval(mins) {
    return $Call.ByID(3522577438, mins);
}

// Private type creation functions
const $$createType0 = models$0.FolderPair.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = sync$0.SyncPreview.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = models$0.AggregateProgress.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = config$0.Config.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = $Create.Array($$createType1);
const $$createType9 = models$0.Peer.createFrom;
const $$createType10 = $Create.Nullable($$createType9);
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = sync$0.SyncEvent.createFrom;
const $$createType13 = $Create.Nullable($$createType12);
const $$createType14 = $Create.Array($$createType13);
const $$createType15 = models$0.TransferProgress.createFrom;
const $$createType16 = $Create.Nullable($$createType15);
const $$createType17 = $Create.Map($Create.Any, $Create.Any);
