// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../time/models.js";

/**
 * SyncEvent represents a sync activity event
 */
export class SyncEvent {
    /**
     * Creates a new SyncEvent instance.
     * @param {Partial<SyncEvent>} [$$source = {}] - The source object to create the SyncEvent.
     */
    constructor($$source = {}) {
        if (!("time" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["time"] = null;
        }
        if (!("type" in $$source)) {
            /**
             * "push", "pull", "delete", "error"
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("folderPair" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["folderPair"] = "";
        }
        if (!("filePath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["filePath"] = "";
        }
        if (!("peerName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["peerName"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SyncEvent instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SyncEvent}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SyncEvent(/** @type {Partial<SyncEvent>} */($$parsedSource));
    }
}

/**
 * SyncPreview represents a preview of sync changes
 */
export class SyncPreview {
    /**
     * Creates a new SyncPreview instance.
     * @param {Partial<SyncPreview>} [$$source = {}] - The source object to create the SyncPreview.
     */
    constructor($$source = {}) {
        if (!("folderPairId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["folderPairId"] = "";
        }
        if (!("peerName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["peerName"] = "";
        }
        if (!("localPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["localPath"] = "";
        }
        if (!("remotePath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["remotePath"] = "";
        }
        if (!("toPush" in $$source)) {
            /**
             * @member
             * @type {(models$0.FileInfo | null)[]}
             */
            this["toPush"] = [];
        }
        if (!("toPull" in $$source)) {
            /**
             * @member
             * @type {(models$0.FileInfo | null)[]}
             */
            this["toPull"] = [];
        }
        if (!("toDelete" in $$source)) {
            /**
             * @member
             * @type {(models$0.FileInfo | null)[]}
             */
            this["toDelete"] = [];
        }
        if (!("pushCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["pushCount"] = 0;
        }
        if (!("pullCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["pullCount"] = 0;
        }
        if (!("deleteCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["deleteCount"] = 0;
        }
        if (!("pushSize" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["pushSize"] = 0;
        }
        if (!("pullSize" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["pullSize"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SyncPreview instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SyncPreview}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType2;
        const $$createField5_0 = $$createType2;
        const $$createField6_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("toPush" in $$parsedSource) {
            $$parsedSource["toPush"] = $$createField4_0($$parsedSource["toPush"]);
        }
        if ("toPull" in $$parsedSource) {
            $$parsedSource["toPull"] = $$createField5_0($$parsedSource["toPull"]);
        }
        if ("toDelete" in $$parsedSource) {
            $$parsedSource["toDelete"] = $$createField6_0($$parsedSource["toDelete"]);
        }
        return new SyncPreview(/** @type {Partial<SyncPreview>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = models$0.FileInfo.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
